name: Release pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Ragtube image
        id: ragtube
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          platforms: linux/amd64,linux/arm64
          target: ragtube
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/ragtube:latest
            ${{ vars.DOCKER_HUB_USERNAME }}/ragtube:${{ github.sha }}
            ghcr.io/${{ github.actor }}/ragtube:latest
            ghcr.io/${{ github.actor }}/ragtube:${{ github.sha }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ vars.DOCKER_HUB_USERNAME }}/ragtube
          subject-digest: ${{ steps.ragtube.outputs.digest }}
          push-to-registry: true

      - name: Build and push Ollama image
        id: ollama
        uses: docker/build-push-action@v6
        with:
          context: ./ollama
          push: true
          platforms: linux/amd64,linux/arm64
          target: ollama
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/ollama:latest
            ${{ vars.DOCKER_HUB_USERNAME }}/ollama:${{ github.sha }}
            ghcr.io/${{ github.actor }}/ollama:latest
            ghcr.io/${{ github.actor }}/ollama:${{ github.sha }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ vars.DOCKER_HUB_USERNAME }}/ollama
          subject-digest: ${{ steps.ollama.outputs.digest }}
          push-to-registry: true

      - name: Build and push Frontend image
        id: frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/ragtube-frontend:latest
            ${{ vars.DOCKER_HUB_USERNAME }}/ragtube-frontend:${{ github.sha }}
            ghcr.io/${{ github.actor }}/ragtube-frontend:latest
            ghcr.io/${{ github.actor }}/ragtube-frontend:${{ github.sha }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ vars.DOCKER_HUB_USERNAME }}/ragtube-frontend
          subject-digest: ${{ steps.frontend.outputs.digest }}
          push-to-registry: true
